task: FedHijack
synthesizer: Pattern

random_seed: 0
batch_size: 64
test_batch_size: 100
lr: 0.1
momentum: 0.9
decay: 0.0005
save_on_epochs: []
optimizer: SGD
log_interval: 100

pretrained: False

scheduler: True

build_task: None


# loss_balance: fixed  # MGDA and fixed and mixed
# mgda_normalize: none
# fixed_scales: {'normal': 1, 'hijack': 0.33}

save_model: False
log: True
tb: False
report_train_loss: True

transform_train: True

fl: True
fl_no_models: 10
fl_total_participants: 100
fl_eta: 10  # 100 / 10, fully replace the global model with updated_parameters
fl_sample_dirichlet: False
fl_dirichlet_alpha: None
fl_diff_privacy:  False
fl_dp_clip: None
fl_dp_noise: None

fl_weight_scale: 1

h_test_data_relabeled_or_converted: True
# fl_number_of_adversaries: 10
# fl_single_epoch_attack: 0     # e.g., 30 means starting attacking on epoch=30, now, fl_number_of_adversaries means how many attacker at this epoch
# fl_multi_epoch_attack: 0      # e.g., 2 means atttack every 2 epoch, 最小是为1
# fl_multi_user_attack: True   # regardless of epochs  指定某几个attackersz则设置为True

loss_tasks:
  - normal
  - hijack
